CREATE TABLE IF NOT EXISTS `person` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(100) NOT NULL,
	`last_name` VARCHAR(100) NOT NULL,
	`address` VARCHAR(100) NOT NULL,
	`gender` VARCHAR(15) NOT NULL,
	PRIMARY KEY (`id`)
) 